# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gezi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_magezi(object):
    def setupUi(self, magezi):
        magezi.setObjectName("magezi")
        magezi.resize(1391, 745)
        magezi.setStyleSheet("}/* Eğer centralWidget\'a uyguluyorsanız, bu daha yaygın ve önerilen yoldur */\n"
"QWidget {\n"
"    background-color: #90A4AE; /* Bir tık daha koyu lacivert/gri tonu */\n"
"}\n"
"\n"
"/* Eğer ana pencereniz bir QMainWindow ise ve direkt ona uyguluyorsanız */\n"
"QMainWindow {\n"
"    background-color: #90A4AE; /* Bir tık daha koyu lacivert/gri tonu */\n"
"}\n"
"\n"
"/* Genellikle önerilmeyen, ancak her şeyi etkileyen genel bir seçici */\n"
"/*\n"
"* {\n"
"    background-color: #90A4AE;\n"
"}\n"
"*/QPushButton {\n"
"    background-color: #E6D3A0; /* Soluk altın sarısı tonu */\n"
"    color: #3C4752; /* Yazı rengini koyu lacivert/gri yapın, okunurluk için */\n"
"    border: 1px solid #CDBA84; /* Kenarlık rengi (soluk altının biraz koyusu) */\n"
"    border-radius: 5px; /* Köşeleri yuvarla (isteğe bağlı) */\n"
"    padding: 5px; /* İç boşluk (isteğe bağlı) */\n"
"}\n"
"QPushButton:hover { /* Fare üzerine geldiğinde renk değiştirme */\n"
"    background-color: #F0E2C0; /* Fare üstünde biraz daha açık soluk altın */\n"
"}\n"
"QPushButton:pressed { /* Butona tıklandığında renk değiştirme */\n"
"    background-color: #D2C092; /* Tıklandığında biraz daha koyu soluk altın */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(magezi)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("/* Eğer centralWidget\'a uyguluyorsanız, bu daha yaygın ve önerilen yoldur */\n"
"QWidget {\n"
"    background-color: #90A4AE; /* Bir tık daha koyu lacivert/gri tonu */\n"
"}\n"
"\n"
"/* Eğer ana pencereniz bir QMainWindow ise ve direkt ona uyguluyorsanız */\n"
"QMainWindow {\n"
"    background-color: #90A4AE; /* Bir tık daha koyu lacivert/gri tonu */\n"
"}\n"
"\n"
"/* Genellikle önerilmeyen, ancak her şeyi etkileyen genel bir seçici */\n"
"/*\n"
"* {\n"
"    background-color: #90A4AE;\n"
"}\n"
"*/QPushButton {\n"
"    background-color: #E6D3A0; /* Soluk altın sarısı tonu */\n"
"    color: #3C4752; /* Yazı rengini koyu lacivert/gri yapın, okunurluk için */\n"
"    border: 1px solid #CDBA84; /* Kenarlık rengi (soluk altının biraz koyusu) */\n"
"    border-radius: 5px; /* Köşeleri yuvarla (isteğe bağlı) */\n"
"    padding: 5px; /* İç boşluk (isteğe bağlı) */\n"
"}\n"
"QPushButton:hover { /* Fare üzerine geldiğinde renk değiştirme */\n"
"    background-color: #F0E2C0; /* Fare üstünde biraz daha açık soluk altın */\n"
"}\n"
"QPushButton:pressed { /* Butona tıklandığında renk değiştirme */\n"
"    background-color: #D2C092; /* Tıklandığında biraz daha koyu soluk altın */\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gbgezi = QtWidgets.QGroupBox(self.centralwidget)
        self.gbgezi.setGeometry(QtCore.QRect(70, 10, 611, 571))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gbgezi.setFont(font)
        self.gbgezi.setObjectName("gbgezi")
        self.tabseh = QtWidgets.QTableWidget(self.gbgezi)
        self.tabseh.setGeometry(QtCore.QRect(10, 150, 591, 261))
        self.tabseh.setStyleSheet("QLineEdit {\n"
"    background-color: #3C4752; /* Daha açık lacivert/gri */\n"
"    color: white; /* Yazı rengi beyaz */\n"
"    border: 1px solid #5A6A78; /* Kenarlık */\n"
"    border-radius: 3px;\n"
"    padding: 2px;\n"
"}")
        self.tabseh.setAlternatingRowColors(True)
        self.tabseh.setObjectName("tabseh")
        self.tabseh.setColumnCount(4)
        self.tabseh.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabseh.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabseh.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabseh.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabseh.setHorizontalHeaderItem(3, item)
        self.tabseh.horizontalHeader().setDefaultSectionSize(148)
        self.tabseh.horizontalHeader().setMinimumSectionSize(50)
        self.tabseh.verticalHeader().setDefaultSectionSize(50)
        self.tabseh.verticalHeader().setHighlightSections(True)
        self.tabseh.verticalHeader().setMinimumSectionSize(33)
        self.pbara = QtWidgets.QPushButton(self.gbgezi)
        self.pbara.setGeometry(QtCore.QRect(340, 90, 101, 28))
        self.pbara.setObjectName("pbara")
        self.liara = QtWidgets.QLineEdit(self.gbgezi)
        self.liara.setGeometry(QtCore.QRect(80, 90, 191, 31))
        self.liara.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"}")
        self.liara.setText("")
        self.liara.setObjectName("liara")
        self.gbyen = QtWidgets.QGroupBox(self.centralwidget)
        self.gbyen.setGeometry(QtCore.QRect(680, 10, 611, 571))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gbyen.setFont(font)
        self.gbyen.setObjectName("gbyen")
        self.pbek = QtWidgets.QPushButton(self.gbyen)
        self.pbek.setGeometry(QtCore.QRect(480, 400, 101, 28))
        self.pbek.setObjectName("pbek")
        self.pbsil = QtWidgets.QPushButton(self.gbyen)
        self.pbsil.setGeometry(QtCore.QRect(480, 440, 101, 28))
        self.pbsil.setObjectName("pbsil")
        self.pbkay = QtWidgets.QPushButton(self.gbyen)
        self.pbkay.setGeometry(QtCore.QRect(240, 530, 121, 28))
        self.pbkay.setObjectName("pbkay")
        self.labseh = QtWidgets.QLabel(self.gbyen)
        self.labseh.setGeometry(QtCore.QRect(70, 430, 71, 31))
        self.labseh.setObjectName("labseh")
        self.cseh = QtWidgets.QComboBox(self.gbyen)
        self.cseh.setGeometry(QtCore.QRect(180, 440, 131, 22))
        self.cseh.setObjectName("cseh")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.cseh.addItem("")
        self.ctur = QtWidgets.QComboBox(self.gbyen)
        self.ctur.setGeometry(QtCore.QRect(180, 490, 131, 22))
        self.ctur.setObjectName("ctur")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.ctur.addItem("")
        self.labtur = QtWidgets.QLabel(self.gbyen)
        self.labtur.setGeometry(QtCore.QRect(70, 490, 55, 16))
        self.labtur.setObjectName("labtur")
        self.labbil = QtWidgets.QLabel(self.gbyen)
        self.labbil.setGeometry(QtCore.QRect(10, 40, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labbil.setFont(font)
        self.labbil.setObjectName("labbil")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.gbyen)
        self.calendarWidget.setGeometry(QtCore.QRect(70, 100, 392, 251))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setAutoFillBackground(False)
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setObjectName("calendarWidget")
        self.labbastar = QtWidgets.QLabel(self.gbyen)
        self.labbastar.setEnabled(True)
        self.labbastar.setGeometry(QtCore.QRect(70, 380, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(True)
        self.labbastar.setFont(font)
        self.labbastar.setToolTip("")
        self.labbastar.setObjectName("labbastar")
        self.labbittar = QtWidgets.QLabel(self.gbyen)
        self.labbittar.setGeometry(QtCore.QRect(290, 380, 71, 31))
        self.labbittar.setObjectName("labbittar")
        self.labbas = QtWidgets.QLabel(self.gbyen)
        self.labbas.setEnabled(False)
        self.labbas.setGeometry(QtCore.QRect(180, 380, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labbas.setFont(font)
        self.labbas.setObjectName("labbas")
        self.labbit = QtWidgets.QLabel(self.gbyen)
        self.labbit.setEnabled(False)
        self.labbit.setGeometry(QtCore.QRect(370, 380, 101, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labbit.setFont(font)
        self.labbit.setObjectName("labbit")
        self.pbd = QtWidgets.QPushButton(self.gbyen)
        self.pbd.setGeometry(QtCore.QRect(480, 480, 101, 28))
        self.pbd.setObjectName("pbd")
        self.pbc = QtWidgets.QPushButton(self.centralwidget)
        self.pbc.setGeometry(QtCore.QRect(630, 600, 121, 41))
        self.pbc.setObjectName("pbc")
        magezi.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(magezi)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1391, 26))
        self.menubar.setObjectName("menubar")
        magezi.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(magezi)
        self.statusbar.setObjectName("statusbar")
        magezi.setStatusBar(self.statusbar)

        self.retranslateUi(magezi)
        QtCore.QMetaObject.connectSlotsByName(magezi)

    def retranslateUi(self, magezi):
        _translate = QtCore.QCoreApplication.translate
        magezi.setWindowTitle(_translate("magezi", "MainWindow"))
        self.gbgezi.setTitle(_translate("magezi", "Gezi Planlarım"))
        item = self.tabseh.horizontalHeaderItem(0)
        item.setText(_translate("magezi", "Şehir"))
        item = self.tabseh.horizontalHeaderItem(1)
        item.setText(_translate("magezi", "Tur Adı"))
        item = self.tabseh.horizontalHeaderItem(2)
        item.setText(_translate("magezi", "Başlangıç Tarihi"))
        item = self.tabseh.horizontalHeaderItem(3)
        item.setText(_translate("magezi", "Bitiş Tarihi"))
        self.pbara.setText(_translate("magezi", "Ara"))
        self.gbyen.setTitle(_translate("magezi", "Yeni Gezi Oluştur"))
        self.pbek.setText(_translate("magezi", "Ekle"))
        self.pbsil.setText(_translate("magezi", "Sil"))
        self.pbkay.setText(_translate("magezi", "Kaydet ve Listele"))
        self.labseh.setText(_translate("magezi", "Şehir seç"))
        self.cseh.setItemText(0, _translate("magezi", "Adana"))
        self.cseh.setItemText(1, _translate("magezi", "Ağrı"))
        self.cseh.setItemText(2, _translate("magezi", "Aksaray"))
        self.cseh.setItemText(3, _translate("magezi", "Ankara"))
        self.cseh.setItemText(4, _translate("magezi", "Artvin"))
        self.cseh.setItemText(5, _translate("magezi", "Aydın"))
        self.cseh.setItemText(6, _translate("magezi", "Balıkesir"))
        self.cseh.setItemText(7, _translate("magezi", "Bartın "))
        self.cseh.setItemText(8, _translate("magezi", "Batman"))
        self.cseh.setItemText(9, _translate("magezi", "Bitlis"))
        self.cseh.setItemText(10, _translate("magezi", "Bodrum"))
        self.cseh.setItemText(11, _translate("magezi", "Bolu"))
        self.cseh.setItemText(12, _translate("magezi", "Bursa"))
        self.cseh.setItemText(13, _translate("magezi", "Burdur"))
        self.cseh.setItemText(14, _translate("magezi", "Çanakkale"))
        self.cseh.setItemText(15, _translate("magezi", "Denizli"))
        self.cseh.setItemText(16, _translate("magezi", "Diyarbakır"))
        self.cseh.setItemText(17, _translate("magezi", "Düzce"))
        self.cseh.setItemText(18, _translate("magezi", "Edirne"))
        self.cseh.setItemText(19, _translate("magezi", "Elazığ"))
        self.cseh.setItemText(20, _translate("magezi", "Erzincan"))
        self.cseh.setItemText(21, _translate("magezi", "Erzurum"))
        self.cseh.setItemText(22, _translate("magezi", "Eskişehir"))
        self.cseh.setItemText(23, _translate("magezi", "Gaziantep"))
        self.cseh.setItemText(24, _translate("magezi", "Giresun"))
        self.cseh.setItemText(25, _translate("magezi", "Hakkari"))
        self.cseh.setItemText(26, _translate("magezi", "Hatay"))
        self.cseh.setItemText(27, _translate("magezi", "Isparta"))
        self.cseh.setItemText(28, _translate("magezi", "İstanbul"))
        self.cseh.setItemText(29, _translate("magezi", "İzmir"))
        self.cseh.setItemText(30, _translate("magezi", "Kars"))
        self.cseh.setItemText(31, _translate("magezi", "Kastamonu"))
        self.cseh.setItemText(32, _translate("magezi", "Kayseri"))
        self.cseh.setItemText(33, _translate("magezi", "Kocaeli"))
        self.cseh.setItemText(34, _translate("magezi", "Konya"))
        self.cseh.setItemText(35, _translate("magezi", "Kütahya"))
        self.cseh.setItemText(36, _translate("magezi", "Malatya"))
        self.cseh.setItemText(37, _translate("magezi", "Manisa"))
        self.cseh.setItemText(38, _translate("magezi", "Mardin"))
        self.cseh.setItemText(39, _translate("magezi", "Mersin"))
        self.cseh.setItemText(40, _translate("magezi", "Muğla"))
        self.cseh.setItemText(41, _translate("magezi", "Muş"))
        self.cseh.setItemText(42, _translate("magezi", "Nevşehir"))
        self.cseh.setItemText(43, _translate("magezi", "Ordu"))
        self.cseh.setItemText(44, _translate("magezi", "Rize"))
        self.cseh.setItemText(45, _translate("magezi", "Sakarya"))
        self.cseh.setItemText(46, _translate("magezi", "Samsun"))
        self.cseh.setItemText(47, _translate("magezi", "Şanlıurfa"))
        self.cseh.setItemText(48, _translate("magezi", "Sinop"))
        self.cseh.setItemText(49, _translate("magezi", "Şırnak"))
        self.cseh.setItemText(50, _translate("magezi", "Tekirdağ"))
        self.cseh.setItemText(51, _translate("magezi", "Trabzon"))
        self.cseh.setItemText(52, _translate("magezi", "Uşak"))
        self.cseh.setItemText(53, _translate("magezi", "Van"))
        self.cseh.setItemText(54, _translate("magezi", "Zonguldak"))
        self.cseh.setItemText(55, _translate("magezi", "Ardahan"))
        self.cseh.setItemText(56, _translate("magezi", "Bingöl"))
        self.cseh.setItemText(57, _translate("magezi", "Adıyaman"))
        self.cseh.setItemText(58, _translate("magezi", "Antalya"))
        self.cseh.setItemText(59, _translate("magezi", "Sivas"))
        self.ctur.setItemText(0, _translate("magezi", "Mavi Rota"))
        self.ctur.setItemText(1, _translate("magezi", "Tarih Yolu"))
        self.ctur.setItemText(2, _translate("magezi", "Ege Serüveni"))
        self.ctur.setItemText(3, _translate("magezi", "Akdeniz Esintisi"))
        self.ctur.setItemText(4, _translate("magezi", "Karadeniz Seyahati"))
        self.ctur.setItemText(5, _translate("magezi", "İç Anadolu Macerası"))
        self.ctur.setItemText(6, _translate("magezi", "Doğu Masalı"))
        self.ctur.setItemText(7, _translate("magezi", "Gurme Turu"))
        self.ctur.setItemText(8, _translate("magezi", "Kültür Şefi"))
        self.ctur.setItemText(9, _translate("magezi", "Vadi Yolculuğu"))
        self.ctur.setItemText(10, _translate("magezi", "Kapadokya Rüyası"))
        self.ctur.setItemText(11, _translate("magezi", "Yeşil Yolculuk"))
        self.ctur.setItemText(12, _translate("magezi", "Buzul Tırmanışı"))
        self.ctur.setItemText(13, _translate("magezi", "Keşif Gezisi"))
        self.ctur.setItemText(14, _translate("magezi", "Antik Diyar"))
        self.labtur.setText(_translate("magezi", "Tur Seç"))
        self.labbil.setText(_translate("magezi", "Başlangıç ve bitiş tarihini takvim üzerinden seçin.Geziler en fazla 3 günlüktür."))
        self.labbastar.setText(_translate("magezi", "Başlangıç Tarihi"))
        self.labbittar.setText(_translate("magezi", "Bitiş Tarihi"))
        self.labbas.setText(_translate("magezi", "1"))
        self.labbit.setText(_translate("magezi", "2"))
        self.pbd.setText(_translate("magezi", "Tarih Güncelle"))
        self.pbc.setText(_translate("magezi", "Çıkış"))
