# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prokulgir.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_makul(object):
    def setupUi(self, makul):
        makul.setObjectName("makul")
        makul.resize(734, 623)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(makul.sizePolicy().hasHeightForWidth())
        makul.setSizePolicy(sizePolicy)
        makul.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setKerning(True)
        makul.setFont(font)
        makul.setToolTip("")
        makul.setStyleSheet("/* Eğer centralWidget\'a uyguluyorsanız, bu daha yaygın ve önerilen yoldur */\n"
"QWidget {\n"
"    background-color: #90A4AE; /* Bir tık daha koyu lacivert/gri tonu */\n"
"}\n"
"\n"
"/* Eğer ana pencereniz bir QMainWindow ise ve direkt ona uyguluyorsanız */\n"
"QMainWindow {\n"
"    background-color: #90A4AE; /* Bir tık daha koyu lacivert/gri tonu */\n"
"}\n"
"\n"
"/* Genellikle önerilmeyen, ancak her şeyi etkileyen genel bir seçici */\n"
"/*\n"
"* {\n"
"    background-color: #90A4AE;\n"
"}\n"
"*/QPushButton {\n"
"    background-color: #E6D3A0; /* Soluk altın sarısı tonu */\n"
"    color: #3C4752; /* Yazı rengini koyu lacivert/gri yapın, okunurluk için */\n"
"    border: 1px solid #CDBA84; /* Kenarlık rengi (soluk altının biraz koyusu) */\n"
"    border-radius: 5px; /* Köşeleri yuvarla (isteğe bağlı) */\n"
"    padding: 5px; /* İç boşluk (isteğe bağlı) */\n"
"}\n"
"QPushButton:hover { /* Fare üzerine geldiğinde renk değiştirme */\n"
"    background-color: #F0E2C0; /* Fare üstünde biraz daha açık soluk altın */\n"
"}\n"
"QPushButton:pressed { /* Butona tıklandığında renk değiştirme */\n"
"    background-color: #D2C092; /* Tıklandığında biraz daha koyu soluk altın */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(makul)
        self.centralwidget.setObjectName("centralwidget")
        self.labturley = QtWidgets.QLabel(self.centralwidget)
        self.labturley.setGeometry(QtCore.QRect(30, 50, 131, 111))
        self.labturley.setText("")
        self.labturley.setPixmap(QtGui.QPixmap("../yeni.png"))
        self.labturley.setScaledContents(True)
        self.labturley.setObjectName("labturley")
        self.gb = QtWidgets.QGroupBox(self.centralwidget)
        self.gb.setGeometry(QtCore.QRect(170, 50, 511, 471))
        self.gb.setTitle("")
        self.gb.setObjectName("gb")
        self.labkulad = QtWidgets.QLabel(self.gb)
        self.labkulad.setGeometry(QtCore.QRect(40, 180, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labkulad.setFont(font)
        self.labkulad.setObjectName("labkulad")
        self.label_3 = QtWidgets.QLabel(self.gb)
        self.label_3.setGeometry(QtCore.QRect(40, 330, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.liad = QtWidgets.QLineEdit(self.gb)
        self.liad.setGeometry(QtCore.QRect(160, 180, 181, 31))
        self.liad.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"}")
        self.liad.setText("")
        self.liad.setObjectName("liad")
        self.lisif = QtWidgets.QLineEdit(self.gb)
        self.lisif.setGeometry(QtCore.QRect(160, 320, 181, 31))
        self.lisif.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"}")
        self.lisif.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lisif.setObjectName("lisif")
        self.chs = QtWidgets.QCheckBox(self.gb)
        self.chs.setGeometry(QtCore.QRect(350, 320, 103, 20))
        self.chs.setObjectName("chs")
        self.pbgir = QtWidgets.QPushButton(self.gb)
        self.pbgir.setGeometry(QtCore.QRect(190, 390, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbgir.sizePolicy().hasHeightForWidth())
        self.pbgir.setSizePolicy(sizePolicy)
        self.pbgir.setMinimumSize(QtCore.QSize(80, 30))
        self.pbgir.setObjectName("pbgir")
        self.labkullan = QtWidgets.QLabel(self.gb)
        self.labkullan.setGeometry(QtCore.QRect(140, 90, 221, 24))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.labkullan.sizePolicy().hasHeightForWidth())
        self.labkullan.setSizePolicy(sizePolicy)
        self.labkullan.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.labkullan.setFont(font)
        self.labkullan.setAlignment(QtCore.Qt.AlignCenter)
        self.labkullan.setObjectName("labkullan")
        self.labepos = QtWidgets.QLabel(self.gb)
        self.labepos.setGeometry(QtCore.QRect(40, 260, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labepos.setFont(font)
        self.labepos.setObjectName("labepos")
        self.lipos = QtWidgets.QLineEdit(self.gb)
        self.lipos.setGeometry(QtCore.QRect(160, 250, 181, 31))
        self.lipos.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"}")
        self.lipos.setText("")
        self.lipos.setObjectName("lipos")
        makul.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(makul)
        self.statusbar.setObjectName("statusbar")
        makul.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(makul)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 734, 26))
        self.menubar.setObjectName("menubar")
        makul.setMenuBar(self.menubar)
        self.actionkategori = QtWidgets.QAction(makul)
        self.actionkategori.setObjectName("actionkategori")
        self.actionurun = QtWidgets.QAction(makul)
        self.actionurun.setObjectName("actionurun")

        self.retranslateUi(makul)
        QtCore.QMetaObject.connectSlotsByName(makul)

    def retranslateUi(self, makul):
        _translate = QtCore.QCoreApplication.translate
        makul.setWindowTitle(_translate("makul", "MainWindow"))
        self.labkulad.setText(_translate("makul", "Kullanıcı Adı"))
        self.label_3.setText(_translate("makul", "Şifre"))
        self.liad.setPlaceholderText(_translate("makul", "Lütfen adınızı soyadınızı girin"))
        self.lisif.setPlaceholderText(_translate("makul", "Şifreniz en az 8 karakter içermelidir"))
        self.chs.setText(_translate("makul", "Şifreyi göster"))
        self.pbgir.setText(_translate("makul", "Giriş yap"))
        self.labkullan.setText(_translate("makul", "Kullanıcı Girişi"))
        self.labepos.setText(_translate("makul", "E-posta"))
        self.lipos.setPlaceholderText(_translate("makul", "Lütfen geçerli bir e-posta girin"))
        self.actionkategori.setText(_translate("makul", "Kategori Tanımları"))
        self.actionurun.setText(_translate("makul", "Ürün Tanımları"))
